version: "3"

services:
  informed365:
    container_name: api
    build:
      context: .
      # relative location of the Dockerfile from docker-compose file
      dockerfile: ./Dockerfile
    image: "informed365:${VERSION_API}"
    # Using default file (.env), any other file doesn't work!!!
    env_file:
      - .env  
    volumes:
      - ${USER_HOME}${CODE_SOURCE}:/var/www/html/project
    ports:
      - "80:80"
  
# DB service configuration here